#!/usr/bin/env bash

sudo dnf install hyprland hypridle waybar swaync hyprpaper fontawesome-fonts-all 
sudo dnf install wayland-devel wayland-protocols-devel hyprlang-devel pango-devel cairo-devel file-devel libglvnd-devel libglvnd-core-devel libjpeg-turbo-devel libwebp-devel libjxl-devel gcc-c++ hyprutils-devel hyprwayland-scanner

