#!/usr/bin/env bash

git clone -b master https://github.com/neovim/neovim.git $HOME/personal/neovim
sudo dnf install cmake gettext lua5.1 liblua5.1-0-dev

# for fedora
sudo dnf install compat-lua-devel
sudo dnf install lua-devel

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo


