#!/usr/bin/env bash

sudo apt install zsh -y
sudo chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Append this line to ~/.zshrc to enable fzf keybindings for Zsh:

source $HOME/personal/fzf/shell/key-bindings.zsh

# Append this line to ~/.zshrc to enable fuzzy auto-completion for Zsh:

source $HOME/personal/fzf/shell/completion.zsh
